version: '3.7'
services:
  api:
    build: .
    ports:
      - 9003:9003
    working_dir: /api
    volumes:
      - ./:/api
    links:
      - mongodb
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
volumes:
  data:
